# fly.toml app configuration file generated for panduta on 2024-09-01T18:37:57+03:00

app = 'panduta'
primary_region = 'cdg' # Paris region, change if needed

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'  # The port Fly.io expects your app to listen on

[http_service]
  internal_port = 8080  # Match the PORT value set above
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[metrics]
  port = 8080
  path = "/metrics"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  [[services.concurrency]]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
